### ISSUE TITLE
Get pictures from some API?

### ISSUE THREAD

**Issue by f1729** [dantehemerson/wallchpaper#3]
Maybe we could integrate a way to consume apis like: 

- https://unsplash.com/developers

to get wallpapers automatically, it can be configure out with tags to get pics more proper for you.

**Comment by dantehemerson** [comment]
@f1729 It's is an awesome feature to do. I was thinking use [Pixabay API](https://pixabay.com/api/docs/#api_search_images) 
due to that Unsplash has [this restriction](https://help.unsplash.com/en/articles/2511245-unsplash-api-guidelines):

> You cannot replicate the core user experience of Unsplash (unofficial clients, wallpaper applications, etc.)
